---
- hosts: spines, leafs
  become: yes
  gather_facts: no
  tasks:
  roles:
    - network_common
    - network_netq
  handlers:
    - include: handlers/main.yml

- hosts: host01,host02
  become: yes
  gather_facts: no
  roles:
    - vxlan_hosts
  handlers:
    - include: handlers/main.yml

- hosts: host03,host04,host05,host06
  become: yes
  gather_facts: no
  roles:
    - docker_hosts
  handlers:
    - include: handlers/main.yml
