---
- hosts: spines, leafs
  become: yes
  gather_facts: no
  tasks:
  roles:
    - network_common
    - network_netq
  handlers:
    - include: handlers/main.yml

- hosts: hosts
  become: yes
  gather_facts: no
  roles:
    - hosts_common
  handlers:
    - include: handlers/main.yml
