---
- hosts: linecards
  become: yes
  gather_facts: no
  tasks:
  roles:
    - network_common
    - linecard_common
    - network_netq
  handlers:
    - include: handlers/main.yml

- hosts: fabriccards
  become: yes
  gather_facts: no
  roles:
    - network_common
    - fabriccard_common
    - network_netq
  handlers:
    - include: handlers/main.yml

- hosts: leafs
  become: yes
  gather_facts: no
  roles:
    - network_common
    - leaf_common
    - network_netq
  handlers:
    - include: handlers/main.yml

- hosts: hosts
  become: yes
  gather_facts: no
  roles:
    - host_common
  handlers:
    - include: handlers/main.yml
